version: '3.7'
networks:
  hooraytalk-network:
    name: hooraytalk-network
    driver: bridge
services:
  nginx-container:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/ssl:/etc/nginx/ssl:ro
    # depends_on:
    #   - telegram-integration-service
    #   - chat-management-service
    #   - openai-service
    #   - discord-crm-service
    networks:
     - hooraytalk-network

  # telegram-integration-service:
  #   image: telegram-integration-service-image
  #   volumes:
  #     - ./nginx/ssl:/etc/telegram-integration-service/ssl:ro
  #   environment:
  #     - SSL_CERT_FILE=/etc/telegram-integration-service/ssl/hooraytalk.crt
  #     - SSL_KEY_FILE=/etc/telegram-integration-service/ssl/hooraytalk.key
  #   expose:
  #     - "443"
  #   networks:
  #     - hooraytalk-network

  # chat-management-service:
  #   image: chat-management-service-image
  #   volumes:
  #     - ./nginx/ssl:/etc/chat-management-service/ssl:ro
  #   environment:
  #     - SSL_CERT_FILE=/etc/chat-management-service/ssl/hooraytalk.crt
  #     - SSL_KEY_FILE=/etc/chat-management-service/ssl/hooraytalk.key
  #   expose:
  #     - "443"
  #   networks:
  #     - hooraytalk-network

  # openai-service:
  #   image: openai-service-image
  #   volumes:
  #     - ./nginx/ssl:/etc/openai-service/ssl:ro
  #   environment:
  #     - SSL_CERT_FILE=/etc/openai-service/ssl/hooraytalk.crt
  #     - SSL_KEY_FILE=/etc/openai-service/ssl/hooraytalk.key
  #   expose:
  #     - "443"
  #   networks:
  #     - hooraytalk-network

  # discord-crm-service:
  #   image: discord-crm-service-image
  #   volumes:
  #     - ./nginx/ssl:/etc/discord-crm-service/ssl:ro
  #   environment:
  #     - SSL_CERT_FILE=/etc/discord-crm-service/ssl/hooraytalk.crt
  #     - SSL_KEY_FILE=/etc/discord-crm-service/ssl/hooraytalk.key
  #   expose:
  #     - "443"
  #   networks:
  #     - hooraytalk-network