version: '3.7'
networks:
  hooraytalk-network:
    name: hooraytalk-network
    driver: bridge
services:
  nginx-service:
    image: nginx:alpine
    ports:
      - "8443:8443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - telegram-adapter-service
    #   - chat-management-service
    #   - openai-service
    #   - discord-crm-service
    networks:
     - hooraytalk-network

  telegram-adapter-service:
    image: openjdk:21-jdk-slim
    volumes:
      - ./nginx/ssl:/etc/telegram-adapter-service/ssl:ro
    environment:
      - SSL_CERT_FILE=/etc/telegram-adapter-service/ssl/hooraytalk.crt
      - SSL_KEY_FILE=/etc/telegram-adapter-service/ssl/hooraytalk.key
    expose:
      - "8443"
    networks:
      - hooraytalk-network

  # chat-management-service:
  #   image: chat-management-service-image
  #   volumes:
  #     - ./nginx/ssl:/etc/chat-management-service/ssl:ro
  #   environment:
  #     - SSL_CERT_FILE=/etc/chat-management-service/ssl/hooraytalk.crt
  #     - SSL_KEY_FILE=/etc/chat-management-service/ssl/hooraytalk.key
  #   expose:
  #     - "8443"
  #   networks:
  #     - hooraytalk-network

  # openai-service:
  #   image: openai-service-image
  #   volumes:
  #     - ./nginx/ssl:/etc/openai-service/ssl:ro
  #   environment:
  #     - SSL_CERT_FILE=/etc/openai-service/ssl/hooraytalk.crt
  #     - SSL_KEY_FILE=/etc/openai-service/ssl/hooraytalk.key
  #   expose:
  #     - "8443"
  #   networks:
  #     - hooraytalk-network

  # discord-crm-service:
  #   image: discord-crm-service-image
  #   volumes:
  #     - ./nginx/ssl:/etc/discord-crm-service/ssl:ro
  #   environment:
  #     - SSL_CERT_FILE=/etc/discord-crm-service/ssl/hooraytalk.crt
  #     - SSL_KEY_FILE=/etc/discord-crm-service/ssl/hooraytalk.key
  #   expose:
  #     - "8443"
  #   networks:
  #     - hooraytalk-network