openapi: 3.0.0
info:
  title: HoorayTalk Message Hub API
  description: This is the HoorayTalk Message Hub API specification for internal use.
  license:
    name: MIT License (MIT)
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: https://message-hub/v1
tags:
  - name: message
    description: Message operations
  - name: health
    description: Health check operations
paths:
  /customer-message:
    post:
      tags:
        - message
      summary: Handle a newly created message from the customer side
      description: Handle a newly created message from the customer. It processes the message and sends it to the target chat(s).
      operationId: handleCustomerMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HandleCustomerMessageRequest'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - IntraServiceApiKeyAuth: [ ]
  /admin-message:
    post:
      tags:
        - message
      summary: Handle a newly created message from the admin side
      description: Handle a newly created message from the admin. It processes the message and sends it to the target chat(s).
      operationId: handleAdminMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HandleAdminMessageRequest'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - IntraServiceApiKeyAuth: [ ]
  /health:
    get:
      tags:
        - health
      summary: Service health check
      description: Service health check endpoint to verify the service is running
      operationId: getHealthStatus
      responses:
        '200':
          description: Service is healthy
        '401':
          description: Unauthorized
components:
  schemas:
    HandleCustomerMessageRequest:
      type: object
      required:
        - bot_id
        - customer_chat_id
        - message
      properties:
        bot_id:
          type: string
          description: Unique identifier of the bot
        customer_chat_id:
          type: string
          description: Unique identifier of the target chat
        message:
          type: string
          description: Text of the message to be sent to the customer
    HandleAdminMessageRequest:
      type: object
      required:
        - bot_id
        - admin_chat_id
        - message
      properties:
        bot_id:
          type: string
          description: Unique identifier of the bot
        admin_chat_id:
          type: string
          description: Unique identifier of the admin-side chat
        message:
          type: string
          description: Text of the message to be sent
  securitySchemes:
    IntraServiceApiKeyAuth:
      type: apiKey
      name: API-KEY
      in: header
